filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'
  dependency_paths:
    - 'vendor/'
build:
  environment:
    php:
      version: '7.4'
  nodes:
    coverage:
      tests:
        override:
          - cp tests/fixtures.dist.ini tests/fixtures.ini
          - cp tests/datacash_magic_numbers.dist.php tests/datacash_magic_numbers.php
          - ./bin/phpunit tests/
    analysis:
      dependencies:
        override:
          - composer install --ignore-platform-reqs --no-interaction
      tests:
        override:
          - php-scrutinizer-run  --enable-security-analysis
